name: yandex_eats_clone_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  yandex_flutter_analysis:
    path: packages/yandex/yandex_flutter_analysis

flutter:
  uses-material-design: true
